---
- name: Install Nginx and configure a simple server
  hosts: all
  become: yes
  vars:
    server_name: miketekin.dev
    document_root: /var/www/html
    app_root: miketekin.dev/public
    ansible_ssh_private_key_file: "~/Documents/ssh-key-2022-12-25.key" # Path to the private key to use

  tasks:
    - name: Update apt cache and install Nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Copy website files to the server's document root
      copy:
        src: "{{ app_root }}"
        dest: "{{ document_root }}"
        mode: preserve # Preserve file permissions

    - name: Apply Nginx template
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/{{ server_name }}
      notify:
        - Restart Nginx

    - name: Enable Nginx site
      file:
        src: /etc/nginx/sites-available/{{ server_name }}
        dest: /etc/nginx/sites-enabled/{{ server_name }}
        state: link
      notify:
        - Restart Nginx

    - name: Allow all access to tcp port 80
      ufw:
        rule: allow
        port: '80'
        proto: tcp

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted