---
- name: Set up server for website hosting
  hosts: all # Run on all hosts
  become: true # Run all tasks as root
  vars:
    # created_username: dev # Username to create - unnecessary on Oracle vps
    ansible_ssh_private_key_file: "~/Documents/ssh-key-2022-12-25.key" # Path to the private key to use

  tasks:
    - name: Update apt and install latest required system packages
      apt:
        pkg: # List of packages to install
          # - ufw # Unnecessary on Oracle vps - already installed
          - fail2ban
          - git
        state: latest # Make sure the latest version is installed
        update_cache: true # Update apt cache before installing

    - name: Upgrade installed apt packages
      apt:
        upgrade: dist
        state: latest # Make sure the latest version is installed
        update_cache: true
      register: upgrade # Register the result of this task
        
    - name: UFW - Allow SSH connections
      community.general.ufw:
        rule: allow
        name: OpenSSH

    - name: UFW - Enable firewall and deny by default
      community.general.ufw:
        state: enabled
        default: deny

    - name: Enable fail2ban service on boot
      service:
        name: fail2ban
        enabled: true
        state: started
      register: fail2ban

    # Unnecessary on Oracle vps - already set up
    #- name: Set up passwordless sudo
    #  lineinfile:
    #    path: /etc/sudoers
    #    state: present
    #    regexp: '^%sudo'
    #    line: '%sudo ALL=(ALL) NOPASSWD:ALL' # Allow sudo without password
    #    validate: 'visudo -cf %s'
    #  register: sudoers

    # Unnecessary on Oracle vps - "ubuntu" user already exists - use that instead
    #- name: Create a new regular user with sudo privileges
    #  user:
    #    name: "{{ created_username }}"
    #    state: present # Make sure the user exists
    #    groups: sudo
    #    append: true
    #    create_home: true

    # Unnecessary on Oracle vps
    #- name: Set authorized key for remote user
    #  ansible.posix.authorized_key:
    #    user: "{{ created_username }}"
    #    state: present
    #    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}" # Read the public key from the local machine

    # Unnecessary on Oracle vps - unable to do anything if logged in as root
    #- name: Disable password authentication for root
    #  lineinfile:
    #    path: /etc/ssh/sshd_config
    #    state: present
    #    regexp: '^#?PermitRootLogin'
    #    line: 'PermitRootLogin prohibit-password'